merged develop and feature/es5, fixed pio-start-all otherwise no changes

diff --git a/bin/pio-start-all b/bin/pio-start-all
--- a/bin/pio-start-all
+++ b/bin/pio-start-all
@@ -26,10 +26,28 @@ export PIO_HOME="$(cd `dirname $0`/..; pwd)"
 . ${PIO_HOME}/bin/load-pio-env.sh
 
 # Elasticsearch
-echo "Starting Elasticsearch..."
-if [ -n "$PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME" ]; then
-  if [ -n "$JAVA_HOME" ]; then
-    JPS=`$JAVA_HOME/bin/jps`
+
+if [ `echo $SOURCE_TYPE | grep -i elasticsearch | wc -l` != 0 ] ; then
+  echo "Starting Elasticsearch..."
+  if [ -n "$PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME" ]; then
+    ELASTICSEARCH_HOME=$PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME
+  elif [ -n "$PIO_STORAGE_SOURCES_ELASTICSEARCH5_HOME" ]; then
+    ELASTICSEARCH_HOME=$PIO_STORAGE_SOURCES_ELASTICSEARCH5_HOME
+  fi
+  if [ -n "$ELASTICSEARCH_HOME" ]; then
+    if [ -n "$JAVA_HOME" ]; then
+      JPS=`$JAVA_HOME/bin/jps`
+    else
+      JPS=`jps`
+    fi
+    if [[ ${JPS} =~ "Elasticsearch" ]]; then
+      echo -e "\033[0;31mElasticsearch is already running. Please use pio-stop-all to try stopping it first.\033[0m"
+      echo -e "\033[0;31mNote: If you started Elasticsearch manually, you will need to kill it manually.\033[0m"
+      echo -e "\033[0;31mAborting...\033[0m"
+      exit 1
+    else
+      $ELASTICSEARCH_HOME/bin/elasticsearch -d -p $PIO_HOME/es.pid
+    fi
   else
     JPS=`jps`
   fi
